version: '3.4'
services:
  api:
    platform: "linux/amd64"
    image: 490946549162.dkr.ecr.us-east-1.amazonaws.com/backend
    ports:
      - "80:8080"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/superprice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: sept23s2
    depends_on:
      - database

  database:
    platform: "linux/amd64"
    container_name: database
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: superprice
      MYSQL_ROOT_PASSWORD: sept23s2
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  adminer:
    platform: "linux/amd64"
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  db:
