version: '3.4'
services:
  web:
    platform: "linux/amd64"
    image: 490946549162.dkr.ecr.us-east-1.amazonaws.com/frontend
    ports:
      - "80:3000"
    environment:
      REACT_APP_API_URL: "http://184.72.144.62"
